runtime: python310

env_variables:
  API_URL: https://www.frbe-kbsb-ksb.be/

handlers:

# root 
- url: /
  static_files: .output/public/index.html
  upload: .output/public/index.html
  secure: always

# url  /capi
- url: /capi
  static_dir: .output/public/capi
  secure: always

# url ending with /
- url: /(.+)/
  static_files: .output/public/\1/index.html
  upload: .output/public/(.+)/index.html
  secure: always

# url with no dot
- url: /([^.]*)$
  static_files: .output/public/\1/index.html
  upload: .output/public/[^.]*/index.html
  secure: always

# the rest
- url: /(.*)
  static_files: .output/public/\1
  upload: .output/public/(.*)
  secure: always