runtime: python310

env_variables:
  API_URL: https://www.frbe-kbsb-ksb.be/

handlers:

# root 
- url: /
  static_files: .output/public/index.html
  upload: .output/public/index.html


# url  /capi
- url: /capi
  static_dir: .output/public/capi

# url ending with /
- url: /(.+)/
  static_files: .output/public/\1/index.html
  upload: .output/public/(.+)/index.html


# url with no dot
- url: /([^.]*)$
  static_files: .output/public/\1/index.html
  upload: .output/public/[^.]*/index.html

# the rest
- url: /(.*)
  static_files: .output/public/\1
  upload: .output/public/(.*)