steps:
  - name: node:16
    entrypoint: yarn
    args: ['install']

  - name: node:16
    entrypoint: yarn
    args: ['generate']


  - name: 'bash'
    script: |
      #!/usr/bin/env bash
      ls -R dist

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: bash 
    args:
      [
        "-c",
        "gcloud config set app/cloud_build_timeout 1600 && gcloud app deploy app_staging.yaml",
      ]
